create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text,
  display_name text,
  provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles
  add column if not exists email text,
  add column if not exists display_name text,
  add column if not exists provider text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.user_profiles
set
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, created_at, now());

alter table public.user_profiles
  alter column created_at set default now(),
  alter column updated_at set default now();

alter table public.user_profiles
  alter column user_id set not null,
  alter column created_at set not null,
  alter column updated_at set not null;

create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz,
  planned_duration double precision,
  actual_duration double precision not null,
  mode text not null,
  status text not null,
  task_tag text,
  summary_note text,
  reflection_mood text,
  is_counted_in_history boolean not null default true,
  trust_level text not null default 'client_reported',
  server_score integer not null default 0,
  last_validated_at timestamptz not null default now(),
  client_payload_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint focus_sessions_user_session_key unique (user_id, session_id)
);

alter table public.focus_sessions
  add column if not exists session_id text,
  add column if not exists user_id uuid,
  add column if not exists start_at timestamptz,
  add column if not exists end_at timestamptz,
  add column if not exists planned_duration double precision,
  add column if not exists actual_duration double precision,
  add column if not exists mode text,
  add column if not exists status text,
  add column if not exists task_tag text,
  add column if not exists summary_note text,
  add column if not exists reflection_mood text,
  add column if not exists is_counted_in_history boolean default true,
  add column if not exists trust_level text default 'client_reported',
  add column if not exists server_score integer default 0,
  add column if not exists last_validated_at timestamptz default now(),
  add column if not exists client_payload_hash text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.focus_sessions
set
  task_tag = nullif(btrim(task_tag), ''),
  summary_note = nullif(btrim(summary_note), ''),
  reflection_mood = nullif(btrim(reflection_mood), ''),
  is_counted_in_history = coalesce(is_counted_in_history, true),
  trust_level = coalesce(nullif(btrim(trust_level), ''), 'client_reported'),
  server_score = coalesce(server_score, 0),
  created_at = coalesce(created_at, start_at, now()),
  updated_at = coalesce(updated_at, created_at, start_at, now()),
  last_validated_at = coalesce(last_validated_at, updated_at, created_at, start_at, now()),
  client_payload_hash = coalesce(
    client_payload_hash,
    md5(
      (
        jsonb_build_object(
          'session_id', session_id,
          'user_id', user_id,
          'start_at', start_at,
          'end_at', end_at,
          'planned_duration', planned_duration,
          'actual_duration', actual_duration,
          'mode', mode,
          'status', status,
          'task_tag', nullif(btrim(task_tag), ''),
          'summary_note', nullif(btrim(summary_note), ''),
          'reflection_mood', nullif(btrim(reflection_mood), ''),
          'is_counted_in_history', coalesce(is_counted_in_history, true)
        )
      )::text
    )
  );

alter table public.focus_sessions
  alter column created_at set default now(),
  alter column updated_at set default now(),
  alter column is_counted_in_history set default true,
  alter column trust_level set default 'client_reported',
  alter column server_score set default 0,
  alter column last_validated_at set default now();

alter table public.focus_sessions
  alter column session_id set not null,
  alter column user_id set not null,
  alter column start_at set not null,
  alter column actual_duration set not null,
  alter column mode set not null,
  alter column status set not null,
  alter column is_counted_in_history set not null,
  alter column trust_level set not null,
  alter column server_score set not null,
  alter column last_validated_at set not null,
  alter column client_payload_hash set not null,
  alter column created_at set not null,
  alter column updated_at set not null;

do $$
declare
  v_constraint_name text;
begin
  for v_constraint_name in
    select con.conname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'focus_sessions'
      and con.contype = 'c'
      and (
        pg_get_constraintdef(con.oid) ilike '%mode%'
        or pg_get_constraintdef(con.oid) ilike '%status%'
        or pg_get_constraintdef(con.oid) ilike '%reflection_mood%'
        or pg_get_constraintdef(con.oid) ilike '%trust_level%'
      )
  loop
    execute format(
      'alter table public.focus_sessions drop constraint if exists %I',
      v_constraint_name
    );
  end loop;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'focus_sessions'
      and con.contype = 'u'
      and pg_get_constraintdef(con.oid) ilike 'unique (user_id, session_id)%'
  )
  and not exists (
    select 1
    from pg_indexes idx
    where idx.schemaname = 'public'
      and idx.tablename = 'focus_sessions'
      and idx.indexdef ilike 'create unique index%'
      and idx.indexdef ilike '%(user_id, session_id)%'
  ) then
    alter table public.focus_sessions
      add constraint focus_sessions_user_session_key unique (user_id, session_id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'focus_sessions'
      and con.conname = 'focus_sessions_mode_check'
  ) then
    alter table public.focus_sessions
      add constraint focus_sessions_mode_check
      check (mode in ('countdown', 'countUp'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'focus_sessions'
      and con.conname = 'focus_sessions_status_check'
  ) then
    alter table public.focus_sessions
      add constraint focus_sessions_status_check
      check (status in ('completed', 'abandoned', 'interrupted'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'focus_sessions'
      and con.conname = 'focus_sessions_reflection_mood_check'
  ) then
    alter table public.focus_sessions
      add constraint focus_sessions_reflection_mood_check
      check (
        reflection_mood is null
        or reflection_mood in ('focused', 'distracted', 'productive', 'calm', 'tired')
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'focus_sessions'
      and con.conname = 'focus_sessions_trust_level_check'
  ) then
    alter table public.focus_sessions
      add constraint focus_sessions_trust_level_check
      check (trust_level in ('client_reported', 'server_verified'));
  end if;
end
$$;

create index if not exists focus_sessions_user_start_idx
  on public.focus_sessions (user_id, start_at desc);

create index if not exists focus_sessions_user_updated_idx
  on public.focus_sessions (user_id, updated_at desc);

alter table public.user_profiles enable row level security;
alter table public.focus_sessions enable row level security;

drop policy if exists "Users can read own profile" on public.user_profiles;
create policy "Users can read own profile"
  on public.user_profiles
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own profile" on public.user_profiles;
create policy "Users can insert own profile"
  on public.user_profiles
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own profile" on public.user_profiles;
create policy "Users can update own profile"
  on public.user_profiles
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

do $$
declare
  v_policy_name text;
begin
  for v_policy_name in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'focus_sessions'
  loop
    execute format('drop policy if exists %I on public.focus_sessions', v_policy_name);
  end loop;
end
$$;

create policy focus_sessions_select_own
  on public.focus_sessions
  for select
  to authenticated
  using (auth.uid() = user_id);

revoke all on table public.focus_sessions from anon, authenticated;
grant select on table public.focus_sessions to authenticated;

do $$
declare
  v_signature text;
begin
  for v_signature in
    select p.oid::regprocedure::text
    from pg_proc p
    join pg_namespace nsp on nsp.oid = p.pronamespace
    where nsp.nspname = 'public'
      and p.proname in ('upsert_client_focus_session', 'delete_client_focus_session')
  loop
    execute format('drop function if exists %s', v_signature);
  end loop;
end
$$;

create function public.upsert_client_focus_session(
  p_session_id text,
  p_start_at timestamptz,
  p_end_at timestamptz,
  p_actual_duration double precision,
  p_mode text,
  p_status text,
  p_planned_duration double precision default null,
  p_task_tag text default null,
  p_summary_note text default null,
  p_reflection_mood text default null,
  p_is_counted_in_history boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid;
  v_now timestamptz := clock_timestamp();
  v_existing public.focus_sessions%rowtype;
  v_saved public.focus_sessions%rowtype;
  v_payload_hash text;
  v_planned_duration double precision;
  v_wall_clock_seconds double precision;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'authentication required';
  end if;

  p_session_id := nullif(btrim(p_session_id), '');
  p_mode := nullif(btrim(p_mode), '');
  p_status := nullif(btrim(p_status), '');
  p_reflection_mood := nullif(btrim(p_reflection_mood), '');
  p_task_tag := nullif(btrim(p_task_tag), '');
  p_summary_note := nullif(btrim(p_summary_note), '');

  if p_session_id is null or char_length(p_session_id) < 3 or char_length(p_session_id) > 128 then
    raise exception 'invalid session_id length';
  end if;

  if p_start_at is null then
    raise exception 'start_at is required';
  end if;

  if p_end_at is null then
    raise exception 'end_at is required';
  end if;

  if p_mode not in ('countdown', 'countUp') then
    raise exception 'invalid mode';
  end if;

  if p_status not in ('completed', 'abandoned', 'interrupted') then
    raise exception 'invalid status';
  end if;

  if p_reflection_mood is not null
     and p_reflection_mood not in ('focused', 'distracted', 'productive', 'calm', 'tired') then
    raise exception 'invalid reflection_mood';
  end if;

  if p_actual_duration is null or p_actual_duration < 0 or p_actual_duration > 43200 then
    raise exception 'invalid actual_duration';
  end if;

  if p_end_at < p_start_at then
    raise exception 'end_at must be greater than or equal to start_at';
  end if;

  if p_start_at > v_now + interval '5 minutes'
     or p_end_at > v_now + interval '5 minutes' then
    raise exception 'start_at and end_at cannot be more than 5 minutes in the future';
  end if;

  if p_mode = 'countdown' then
    if p_planned_duration is null or p_planned_duration < 60 or p_planned_duration > 7200 then
      raise exception 'invalid planned_duration for countdown mode';
    end if;
    v_planned_duration := p_planned_duration;
  else
    v_planned_duration := null;
  end if;

  v_wall_clock_seconds := extract(epoch from (p_end_at - p_start_at));

  if p_actual_duration > v_wall_clock_seconds + 300 then
    raise exception 'actual_duration exceeds wall clock allowance';
  end if;

  select *
  into v_existing
  from public.focus_sessions
  where user_id = v_user_id
    and session_id = p_session_id
  limit 1;

  if found and v_existing.trust_level = 'server_verified' then
    raise exception 'server_verified session cannot be overwritten';
  end if;

  if exists (
    select 1
    from public.focus_sessions fs
    where fs.user_id = v_user_id
      and fs.trust_level = 'server_verified'
      and fs.session_id <> p_session_id
      and tstzrange(fs.start_at, coalesce(fs.end_at, 'infinity'::timestamptz), '[)')
          && tstzrange(p_start_at, p_end_at, '[)')
  ) then
    raise exception 'session overlaps a server_verified session';
  end if;

  v_payload_hash := md5(
    (
      jsonb_build_object(
        'session_id', p_session_id,
        'user_id', v_user_id,
        'start_at', p_start_at,
        'end_at', p_end_at,
        'planned_duration', v_planned_duration,
        'actual_duration', p_actual_duration,
        'mode', p_mode,
        'status', p_status,
        'task_tag', p_task_tag,
        'summary_note', p_summary_note,
        'reflection_mood', p_reflection_mood,
        'is_counted_in_history', coalesce(p_is_counted_in_history, true)
      )
    )::text
  );

  insert into public.focus_sessions (
    session_id,
    user_id,
    start_at,
    end_at,
    planned_duration,
    actual_duration,
    mode,
    status,
    task_tag,
    summary_note,
    reflection_mood,
    is_counted_in_history,
    trust_level,
    server_score,
    last_validated_at,
    client_payload_hash,
    created_at,
    updated_at
  )
  values (
    p_session_id,
    v_user_id,
    p_start_at,
    p_end_at,
    v_planned_duration,
    p_actual_duration,
    p_mode,
    p_status,
    p_task_tag,
    p_summary_note,
    p_reflection_mood,
    coalesce(p_is_counted_in_history, true),
    'client_reported',
    0,
    v_now,
    v_payload_hash,
    coalesce(v_existing.created_at, p_start_at, v_now),
    v_now
  )
  on conflict (user_id, session_id) do update
  set
    start_at = excluded.start_at,
    end_at = excluded.end_at,
    planned_duration = excluded.planned_duration,
    actual_duration = excluded.actual_duration,
    mode = excluded.mode,
    status = excluded.status,
    task_tag = excluded.task_tag,
    summary_note = excluded.summary_note,
    reflection_mood = excluded.reflection_mood,
    is_counted_in_history = excluded.is_counted_in_history,
    trust_level = 'client_reported',
    server_score = 0,
    last_validated_at = excluded.last_validated_at,
    client_payload_hash = excluded.client_payload_hash,
    updated_at = excluded.updated_at
  where public.focus_sessions.trust_level <> 'server_verified'
  returning *
  into v_saved;

  if not found then
    raise exception 'server_verified session cannot be overwritten';
  end if;

  return to_jsonb(v_saved);
end
$$;

create function public.delete_client_focus_session(
  p_session_id text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid;
  v_existing public.focus_sessions%rowtype;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'authentication required';
  end if;

  p_session_id := nullif(btrim(p_session_id), '');

  if p_session_id is null or char_length(p_session_id) < 3 or char_length(p_session_id) > 128 then
    raise exception 'invalid session_id length';
  end if;

  select *
  into v_existing
  from public.focus_sessions
  where user_id = v_user_id
    and session_id = p_session_id
  limit 1;

  if not found then
    return;
  end if;

  if v_existing.trust_level = 'server_verified' then
    raise exception 'server_verified session cannot be deleted';
  end if;

  delete from public.focus_sessions
  where user_id = v_user_id
    and session_id = p_session_id
    and trust_level <> 'server_verified';
end
$$;

revoke all on function public.upsert_client_focus_session(
  text,
  timestamptz,
  timestamptz,
  double precision,
  text,
  text,
  double precision,
  text,
  text,
  text,
  boolean
) from public, anon, authenticated;

revoke all on function public.delete_client_focus_session(text)
from public, anon, authenticated;

grant execute on function public.upsert_client_focus_session(
  text,
  timestamptz,
  timestamptz,
  double precision,
  text,
  text,
  double precision,
  text,
  text,
  text,
  boolean
) to authenticated, service_role;

grant execute on function public.delete_client_focus_session(text)
to authenticated, service_role;