create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text,
  display_name text,
  provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz,
  planned_duration double precision,
  actual_duration double precision not null,
  mode text not null check (mode in ('countdown', 'countUp')),
  status text not null check (status in ('completed', 'abandoned', 'interrupted')),
  task_tag text,
  summary_note text,
  reflection_mood text check (
    reflection_mood in ('focused', 'distracted', 'productive', 'calm', 'tired')
  ),
  is_counted_in_history boolean not null default true,
  created_at timestamptz not null,
  updated_at timestamptz not null default now(),
  unique (user_id, session_id)
);

create index if not exists focus_sessions_user_start_idx
  on public.focus_sessions (user_id, start_at desc);

create index if not exists focus_sessions_user_updated_idx
  on public.focus_sessions (user_id, updated_at desc);

alter table public.user_profiles enable row level security;
alter table public.focus_sessions enable row level security;

drop policy if exists "Users can read own profile" on public.user_profiles;
create policy "Users can read own profile"
  on public.user_profiles
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own profile" on public.user_profiles;
create policy "Users can insert own profile"
  on public.user_profiles
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own profile" on public.user_profiles;
create policy "Users can update own profile"
  on public.user_profiles
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can read own focus sessions" on public.focus_sessions;
create policy "Users can read own focus sessions"
  on public.focus_sessions
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own focus sessions" on public.focus_sessions;
create policy "Users can insert own focus sessions"
  on public.focus_sessions
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own focus sessions" on public.focus_sessions;
create policy "Users can update own focus sessions"
  on public.focus_sessions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own focus sessions" on public.focus_sessions;
create policy "Users can delete own focus sessions"
  on public.focus_sessions
  for delete
  using (auth.uid() = user_id);